CONFIG_MAIN_STACK_SIZE=6144

CONFIG_LOG=y
CONFIG_THREAD_RUNTIME_STATS=y
CONFIG_SCHED_THREAD_USAGE_ALL=y
CONFIG_SYS_HEAP_RUNTIME_STATS=y

CONFIG_NETWORKING=y
CONFIG_NET_MGMT=y
CONFIG_NET_MGMT_EVENT=y
CONFIG_NET_MGMT_EVENT_INFO=y
CONFIG_NET_CONNECTION_MANAGER=y
CONFIG_NET_IPV4=y
CONFIG_NET_TCP=y
CONFIG_NET_UDP=y
CONFIG_NET_SOCKETS=y
CONFIG_NET_DHCPV4=y

CONFIG_WIFI=y
CONFIG_NET_L2_WIFI_MGMT=y

CONFIG_HTTP_SERVER=y
CONFIG_HTTP_SERVER_RESOURCE_WILDCARD=y
CONFIG_HTTP_SERVER_COMPRESSION=y
CONFIG_HTTP_SERVER_NUM_SERVICES=1
CONFIG_HTTP_SERVER_MAX_CLIENTS=4
CONFIG_HTTP_SERVER_CLIENT_BUFFER_SIZE=2048

CONFIG_POSIX_API=y
CONFIG_EVENTFD=y
CONFIG_FDTABLE=y
CONFIG_ZVFS_POLL_MAX=16

CONFIG_FLASH=y
CONFIG_FLASH_MAP=y
CONFIG_FILE_SYSTEM=y
CONFIG_FILE_SYSTEM_MKFS=y
CONFIG_FILE_SYSTEM_LITTLEFS=y

CONFIG_APP_WEB_CONTENT_FROM_FIRMWARE=y
#CONFIG_APP_WEB_CONTENT_FROM_FILESYSTEM=y
